services:

  app:
    image: ghcr.io/alexdaiii/simple-image-service:v0.3.0
    ports:
      - "8000:8000"
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - POLICY_AUD=${POLICY_AUD}
      - TEAM_DOMAIN=${TEAM_DOMAIN}
      - HOST=${HOST}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_ORIGINS=*
    volumes:
      # include these or it will auto-create anonymous volumes
      - ./data:/data
      - ./config:/config
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: '512M'

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - app
      - nginx
    deploy:
      resources:
        limits:
          memory: '256M'
          cpus: '0.25'


  nginx:
    image: nginx:1.27
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'